import React, { useState } from "react";
import {
  StyleSheet,
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  Alert,
  Platform,
} from "react-native";
import * as ImagePicker from "expo-image-picker";
import {
  uploadFiles,
  UnifiedUploadConfig,
  FileUploadConfig,
  UploadProgress,
} from "@hubspire/react-native-chunk-upload";

// Configuration - Update this to match your backend URL
const API_BASE_URL = __DEV__
  ? Platform.OS === "android"
    ? "http://10.0.2.2:3000" // Android emulator
    : "http://localhost:3000" // iOS simulator / web
  : "https://your-backend-url.com";

const getUploadUrl = async ({
  uploadType,
  mediaType,
  contentType,
  extension,
  totalParts,
}: any) => {
  // Single unified endpoint - backend handles chunked, simple, and thumbnail uploads
  const response = await fetch(`${API_BASE_URL}/api/upload/url`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      uploadType,
      mediaType, // Not required for thumbnails
      contentType,
      extension,
      totalParts, // Only used for chunked uploads
    }),
  });
  if (!response.ok) throw new Error("Failed to get upload URL");
  return response.json();
  // Returns { urls, key, uploadId } for chunked or { url, key } for simple/thumbnail
};

const markUploadComplete = async ({ eTags, key, uploadId }: any) => {
  const response = await fetch(`${API_BASE_URL}/api/upload/complete`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ eTags, key, uploadId }),
  });
  if (!response.ok) throw new Error("Failed to complete upload");
  return response.json();
};

export default function Index() {
  const [selectedFiles, setSelectedFiles] = useState<FileUploadConfig[]>([]);
  const [uploadProgress, setUploadProgress] = useState<
    Map<number, UploadProgress>
  >(new Map());
  const [overallProgress, setOverallProgress] = useState(0);
  const [isUploading, setIsUploading] = useState(false);
  const [uploadResults, setUploadResults] = useState<any[]>([]);

  const pickImage = async () => {
    const { status } = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (status !== "granted") {
      Alert.alert("Permission needed", "Please grant camera roll permissions");
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsMultipleSelection: true,
      quality: 1,
    });

    if (!result.canceled && result.assets) {
      // Process assets - thumbnails will be auto-generated by the package for videos
      const files: FileUploadConfig[] = result.assets.map((asset, index) => {
        const extension = asset.uri.split(".").pop()?.toLowerCase() || "jpg";
        const contentType =
          asset.type === "video" ? `video/${extension}` : `image/${extension}`;

        return {
          fileIndex: 0, // Will be set correctly in the functional update
          filePath: asset.uri,
          fileSize: asset.fileSize || 0,
          mediaType: asset.type === "video" ? "video" : "photo",
          contentType,
          extension,
        };
      });

      // Use functional update to ensure correct fileIndex based on current state
      setSelectedFiles((prev) => {
        // Calculate indices based on the current state at the time of update
        const filesWithCorrectIndices = files.map((file, index) => ({
          ...file,
          fileIndex: prev.length + index,
        }));
        return [...prev, ...filesWithCorrectIndices];
      });
    }
  };

  const pickCamera = async () => {
    const { status } = await ImagePicker.requestCameraPermissionsAsync();
    if (status !== "granted") {
      Alert.alert("Permission needed", "Please grant camera permissions");
      return;
    }

    const result = await ImagePicker.launchCameraAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      quality: 1,
    });

    if (!result.canceled && result.assets[0]) {
      const asset = result.assets[0];
      const extension = asset.uri.split(".").pop()?.toLowerCase() || "jpg";
      const contentType =
        asset.type === "video" ? `video/${extension}` : `image/${extension}`;

      // Use functional update to ensure correct fileIndex based on current state
      setSelectedFiles((prev) => {
        const file: FileUploadConfig = {
          fileIndex: prev.length,
          filePath: asset.uri,
          fileSize: asset.fileSize || 0,
          mediaType: asset.type === "video" ? "video" : "photo",
          contentType,
          extension,
        };
        return [...prev, file];
      });
    }
  };

  const uploadConfig: UnifiedUploadConfig = {
    getUploadUrl,
    markUploadComplete,
    onProgress: (progress) => {
      setUploadProgress((prev) => {
        const newMap = new Map(prev);
        newMap.set(progress.fileIndex, {
          ...progress,
          percentComplete: progress.percentComplete || 0,
          uploadedBytes: progress.uploadedBytes || 0,
          totalBytes: progress.totalBytes || 0,
        });
        return newMap;
      });
    },
    onTotalProgress: (progress) => {
      // Update overall progress across all files
      setOverallProgress(progress.overallPercentComplete);
    },
  };

  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      Alert.alert("No files", "Please select files first");
      return;
    }

    setIsUploading(true);
    setUploadProgress(new Map());
    setOverallProgress(0);
    setUploadResults([]);

    try {
      // uploadFiles automatically switches between chunked and simple uploads
      // based on file size (files >= chunkThresholdBytes use chunked, others use simple)
      const results = await uploadFiles(selectedFiles, uploadConfig);
      setUploadResults(results);

      // Update progress with failure reasons from results
      setUploadProgress((prev) => {
        const newMap = new Map(prev);
        results.forEach((result) => {
          if (result.status === "failed" && result.error) {
            const existing = newMap.get(result.fileIndex);
            if (existing) {
              const errorStr =
                typeof result.error === "string"
                  ? result.error
                  : String(result.error || "Upload failed");
              newMap.set(result.fileIndex, {
                ...existing,
                status: "failed",
                error: errorStr,
              });
            }
          }
        });
        return newMap;
      });

      const failed = results.filter((r) => r.status === "failed");
      if (failed.length > 0) {
        Alert.alert(
          "Upload completed with errors",
          `${results.length - failed.length} succeeded, ${failed.length} failed`
        );
      } else {
        Alert.alert(
          "Success",
          `All ${results.length} files uploaded successfully!`
        );
      }
    } catch (error: any) {
      Alert.alert("Upload error", error.message || "Failed to upload files");
    } finally {
      setIsUploading(false);
    }
  };

  const clearFiles = async () => {
    try {
      // Clear files from LocalStack
      const response = await fetch(`${API_BASE_URL}/api/files`, {
        method: "DELETE",
      });

      if (!response.ok) {
        const errorData = await response.json();
        Alert.alert(
          "Clear Error",
          errorData.message || "Failed to clear files from server"
        );
      } else {
        const data = await response.json();
        if (data.deleted > 0) {
          Alert.alert(
            "Files Cleared",
            `Deleted ${data.deleted} file(s) from server${
              data.failed > 0 ? ` (${data.failed} failed)` : ""
            }`
          );
        }
      }
    } catch (error: any) {
      console.error("Error clearing files:", error);
      // Don't show error alert - just clear local state anyway
    }

    // Clear local state
    setSelectedFiles([]);
    setUploadProgress(new Map());
    setOverallProgress(0);
    setUploadResults([]);
  };

  const removeFile = (index: number) => {
    setSelectedFiles(selectedFiles.filter((_, i) => i !== index));
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + " " + sizes[i];
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Chunked Upload Example</Text>
      <Text style={styles.subtitle}>{`Backend: ${API_BASE_URL}`}</Text>

      <View style={styles.buttonRow}>
        <TouchableOpacity style={styles.button} onPress={pickImage}>
          <Text style={styles.buttonText}>Pick from Library</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={pickCamera}>
          <Text style={styles.buttonText}>Take Photo/Video</Text>
        </TouchableOpacity>
      </View>

      {selectedFiles.length > 0 && (
        <>
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>
              Selected Files ({selectedFiles.length})
            </Text>
            {selectedFiles.map((file, index) => (
              <View key={index} style={styles.fileItem}>
                <View style={styles.fileInfo}>
                  <Text style={styles.fileName}>
                    {file.mediaType} - {formatFileSize(file.fileSize)}
                  </Text>
                  <Text style={styles.filePath}>
                    {file.filePath.split("/").pop()}
                  </Text>
                </View>
                <TouchableOpacity onPress={() => removeFile(index)}>
                  <Text style={styles.removeButton}>×</Text>
                </TouchableOpacity>
              </View>
            ))}
          </View>

          <TouchableOpacity
            style={[
              styles.uploadButton,
              isUploading && styles.uploadButtonDisabled,
            ]}
            onPress={handleUpload}
            disabled={isUploading}
          >
            <Text style={styles.uploadButtonText}>
              {isUploading ? "Uploading..." : "Upload Files"}
            </Text>
          </TouchableOpacity>

          <TouchableOpacity style={styles.clearButton} onPress={clearFiles}>
            <Text style={styles.clearButtonText}>Clear All</Text>
          </TouchableOpacity>
        </>
      )}

      {overallProgress > 0 && (
        <View style={styles.progressSection}>
          <Text style={styles.sectionTitle}>Overall Progress</Text>
          <View style={styles.progressBar}>
            <View
              style={[styles.progressFill, { width: `${overallProgress}%` }]}
            />
          </View>
          <Text style={styles.progressText}>
            {Math.round(overallProgress)}%
          </Text>
        </View>
      )}

      {uploadProgress.size > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>File Progress</Text>
          {Array.from(uploadProgress.values()).map((progress) => (
            <View key={progress.fileIndex} style={styles.progressItem}>
              <Text style={styles.progressLabel}>
                File {progress.fileIndex + 1}:{" "}
                {Math.round(progress.percentComplete || 0)}%
              </Text>
              <View style={styles.progressBar}>
                <View
                  style={[
                    styles.progressFill,
                    {
                      width: `${progress.percentComplete || 0}%`,
                      backgroundColor:
                        progress.status === "failed"
                          ? "#ff4444"
                          : progress.status === "completed"
                          ? "#44ff44"
                          : "#4444ff",
                    },
                  ]}
                />
              </View>
              {progress.status === "failed" && (
                <Text style={styles.errorText}>
                  {typeof progress.error === "string"
                    ? progress.error
                    : progress.error?.message || "Upload failed"}
                </Text>
              )}
            </View>
          ))}
        </View>
      )}

      {uploadResults.length > 0 && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Upload Results</Text>
          {uploadResults.map((result, index) => (
            <View key={index} style={styles.resultItem}>
              <Text style={styles.resultText}>
                File{" "}
                {typeof result.fileIndex === "number"
                  ? result.fileIndex + 1
                  : index + 1}
                :{" "}
                {result.status === "failed" ? (
                  <Text style={styles.errorText}>
                    Failed -{" "}
                    {typeof result.error === "string"
                      ? result.error
                      : result.error?.message || "Upload failed"}
                  </Text>
                ) : (
                  <Text style={styles.successText} numberOfLines={0}>
                    Success! Key: {result.key || "N/A"}
                  </Text>
                )}
              </Text>
            </View>
          ))}
        </View>
      )}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  content: {
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  button: {
    flex: 1,
    backgroundColor: "#007AFF",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
  },
  uploadButton: {
    flex: 1,
    backgroundColor: "#34C759",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  uploadButtonDisabled: {
    opacity: 0.5,
  },
  uploadButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  clearButton: {
    backgroundColor: "#FF3B30",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  clearButtonText: {
    color: "#fff",
    fontWeight: "600",
  },
  section: {
    marginTop: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  fileItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    marginBottom: 8,
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 14,
    fontWeight: "600",
  },
  filePath: {
    fontSize: 12,
    color: "#666",
    marginTop: 4,
  },
  removeButton: {
    fontSize: 24,
    color: "#FF3B30",
    fontWeight: "bold",
  },
  progressSection: {
    marginTop: 20,
    marginBottom: 20,
  },
  progressItem: {
    marginBottom: 15,
  },
  progressLabel: {
    fontSize: 14,
    marginBottom: 5,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#e0e0e0",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#007AFF",
    borderRadius: 4,
  },
  progressText: {
    marginTop: 5,
    fontSize: 12,
    color: "#666",
  },
  errorText: {
    color: "#FF3B30",
    fontSize: 12,
    marginTop: 5,
  },
  successText: {
    color: "#34C759",
    fontSize: 12,
  },
  resultItem: {
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    marginBottom: 8,
  },
  resultText: {
    fontSize: 14,
    flexWrap: "wrap",
  },
});
